import { and,desc,eq } from "drizzle-orm";
import { z } from "zod";
import { sosExecutions } from "@/db/schema";
import type { AppDatabase } from "@/db/client";
import type { SosExperienceState } from "./types";

const traffic=z.enum(["green","yellow","red",""]);
export const sosStateSchema=z.object({executionId:z.uuid().optional(),step:z.number().int().min(0).max(8),startedAt:z.iso.datetime(),completedAt:z.iso.datetime().optional(),pauseEndsAt:z.iso.datetime(),pauseReason:z.string().max(2000),initialIntensity:z.number().int().min(1).max(10),emotions:z.array(z.string().max(80)).max(12),expectedOutcome:z.string().max(100),realFact:z.string().max(3000),anxietyStory:z.string().max(3000),speakingPart:z.string().max(100),safeAction:z.string().max(200),unsentMessage:z.string().max(5000),expectedResponse:z.string().max(2000),messageSaved:z.boolean(),selectedAnchor:z.string().max(500),finalIntensity:z.number().int().min(1).max(10),trafficLightResult:traffic,status:z.enum(["in_progress","completed"])});
const legacySchema=z.object({messageText:z.string().trim().min(1).max(5000),expectedResponse:z.string().trim().min(1).max(2000),desiredOutcome:z.enum(["claridad","atencion","reconciliacion","respuesta","alivio","otra"]),emotionBefore:z.number().int().min(1).max(10),emotionAfter:z.number().int().min(1).max(10).optional(),completed:z.boolean().default(false)});
function values(state:SosExperienceState,tenantId:string,userId:string){return {tenantId,userId,messageText:JSON.stringify(state),expectedResponse:state.expectedResponse||"Sin respuesta esperada",desiredOutcome:"otra",emotionBefore:state.initialIntensity,emotionAfter:state.finalIntensity,status:state.status==="completed"?"completed":"saved",completedAt:state.status==="completed"?new Date(state.completedAt??Date.now()):null}}
export async function saveSosExecution(db:AppDatabase,tenantId:string,userId:string,input:unknown){const modern=sosStateSchema.safeParse(input);if(modern.success)return db.insert(sosExecutions).values(values(modern.data,tenantId,userId)).returning({id:sosExecutions.id});const value=legacySchema.parse(input);return db.insert(sosExecutions).values({tenantId,userId,messageText:value.messageText,expectedResponse:value.expectedResponse,desiredOutcome:value.desiredOutcome,emotionBefore:value.emotionBefore,emotionAfter:value.emotionAfter,status:value.completed?"completed":"saved",completedAt:value.completed?new Date():null}).returning({id:sosExecutions.id});}
export async function updateSosExecution(db:AppDatabase,tenantId:string,userId:string,id:string,input:unknown){const state=sosStateSchema.parse(input);return db.update(sosExecutions).set(values(state,tenantId,userId)).where(and(eq(sosExecutions.id,id),eq(sosExecutions.tenantId,tenantId),eq(sosExecutions.userId,userId))).returning({id:sosExecutions.id});}
export async function getLatestSosState(db:AppDatabase,tenantId:string,userId:string):Promise<SosExperienceState|undefined>{const [row]=await db.select({id:sosExecutions.id,messageText:sosExecutions.messageText}).from(sosExecutions).where(and(eq(sosExecutions.tenantId,tenantId),eq(sosExecutions.userId,userId))).orderBy(desc(sosExecutions.createdAt)).limit(1);if(!row)return;try{const parsed=sosStateSchema.parse(JSON.parse(row.messageText));return {...parsed,executionId:row.id}}catch{return}}
export async function listSosExecutions(db:AppDatabase,tenantId:string,userId:string){return db.select({id:sosExecutions.id,status:sosExecutions.status,createdAt:sosExecutions.createdAt,messageText:sosExecutions.messageText,expectedResponse:sosExecutions.expectedResponse,desiredOutcome:sosExecutions.desiredOutcome,emotionBefore:sosExecutions.emotionBefore,emotionAfter:sosExecutions.emotionAfter}).from(sosExecutions).where(and(eq(sosExecutions.tenantId,tenantId),eq(sosExecutions.userId,userId))).orderBy(desc(sosExecutions.createdAt));}
