import {readFileSync} from "node:fs";import path from "node:path";import {renderToStaticMarkup} from "react-dom/server";import {describe,expect,it} from "vitest";import {CreatorMediaSection,ExperienceEngine,ExperienceNavigator,PersonalResultSection,hasQuickEntry} from "@/components/experience/experience-engine";import {brandingToCssVariables} from "@/features/tenants/branding";import {loadContent} from "./loader";
const fixtureRoot=path.join(process.cwd(),"tests/fixtures/content");
describe("Experience Engine generalization",()=>{
 it("uses published content to build navigation for both niches",async()=>{const [mnle]=await loadContent();const [sewing]=await loadContent(fixtureRoot);const first=mnle.modules[0].sections!.filter(section=>section.status==="published"),second=sewing.modules[0].sections!.filter(section=>section.status==="published");const a=renderToStaticMarkup(<ExperienceNavigator sections={first} current={0} onSelect={()=>undefined}/>),b=renderToStaticMarkup(<ExperienceNavigator sections={second} current={0} onSelect={()=>undefined}/>);expect(a).toContain("el método P.A.U.S.A.");expect(b).toContain("Materiales");expect(a).not.toContain("Materiales");expect(first.map(section=>section.type)).not.toEqual(second.map(section=>section.type))});
 it("supports project mode and optional quick entry",async()=>{const [mnle]=await loadContent();const [sewing]=await loadContent(fixtureRoot);expect(hasQuickEntry(mnle.modules[0])).toBe(true);expect(hasQuickEntry(sewing.modules[0])).toBe(false);expect(sewing.modules[0]).toMatchObject({experienceType:"project",presentationMode:"project"})});
 it("renders different creators through the same section",async()=>{const [mnle]=await loadContent();const [sewing]=await loadContent(fixtureRoot);for(const content of [mnle,sewing]){const section=content.modules[0].sections!.find(value=>value.type==="creator_message")!;const html=renderToStaticMarkup(<CreatorMediaSection section={section} assets={Object.fromEntries(content.assets.map(asset=>[asset.key,asset]))} answers={{}} onAnswer={()=>undefined}/>);expect(html).toContain(section.creator!.displayName)}});
 it("creates personal results from unrelated response models",async()=>{const [mnle]=await loadContent();const [sewing]=await loadContent(fixtureRoot);const therapeutic=mnle.modules[0].sections!.find(value=>value.type==="result")!,project=sewing.modules[0].sections!.find(value=>value.type==="result")!;const first=renderToStaticMarkup(<PersonalResultSection section={therapeutic} assets={{}} answers={{"frase-ancla":"Mi elección"}} onAnswer={()=>undefined}/>),second=renderToStaticMarkup(<PersonalResultSection section={project} assets={{}} answers={{acabado:"doblado"}} onAnswer={()=>undefined}/>);expect(first).toContain("Mi elección");expect(second).toContain("Acabado doblado")});
 it("keeps shared components free from tenant copy and derives branding from tokens",()=>{const source=readFileSync(path.join(process.cwd(),"src/components/experience/experience-engine.tsx"),"utf8");expect(source).not.toMatch(/Janny|P\.A\.U\.S\.A\.|MNLE/);const base={colors:{background:"#fff",surface:"#fff",surfaceMuted:"#eee",primary:"#111",primaryForeground:"#fff",secondary:"#222",secondaryForeground:"#fff",accent:"#333",accentForeground:"#fff",text:"#111",textMuted:"#555",border:"#ddd",success:"#080",warning:"#880",danger:"#800"},typography:{headingFont:"serif",bodyFont:"sans-serif"},radius:{card:"1rem",button:".5rem"},assets:{logo:"",icon:"",cover:""},supportEmail:"a@example.com",tagline:"A"};expect(brandingToCssVariables(base)["--primary"]).toBe("#111");expect(brandingToCssVariables({...base,colors:{...base.colors,primary:"#456789"}})["--primary"]).toBe("#456789")});
 it("separates the standard journey from the quick entry",async()=>{const [content]=await loadContent(),experience=content.modules[0],assets=Object.fromEntries(content.assets.map(asset=>[asset.key,asset]));const standard=renderToStaticMarkup(<ExperienceEngine experience={experience} assets={assets} entryMode="standard"/>),quick=renderToStaticMarkup(<ExperienceEngine experience={experience} assets={assets} entryMode="quick"/>);expect(standard).toContain("No le escribas todavía");expect(standard).not.toContain("textarea");expect(quick).toContain("Audio de emergencia");expect(quick).not.toContain("No le escribas todavía")});
 it("keeps real routes protected and email disabled",()=>{const dashboard=readFileSync(path.join(process.cwd(),"src/app/page.tsx"),"utf8"),moduleRoute=readFileSync(path.join(process.cwd(),"src/app/demo/modulo-0/page.tsx"),"utf8"),protectedLayout=readFileSync(path.join(process.cwd(),"src/app/app/layout.tsx"),"utf8"),stack=readFileSync(path.join(process.cwd(),"infrastructure/stack.prod.yml"),"utf8");expect(dashboard).toContain('href="/demo/modulo-0"');expect(dashboard).toContain('href="/demo/sos"');expect(moduleRoute).toContain('entryMode="standard"');expect(protectedLayout).toContain("requireSession");expect(stack).toContain('EMAIL_ENABLED: "false"')});
});
