import { isPublishedAsset,type ContentAsset } from "./schema";

export type VideoEvent="ready"|"play"|"pause"|"progress"|"ended"|"error";
export interface VideoPlayerAdapter {provider:"youtube"|"bunny";render:(asset:ContentAsset,title:string)=>React.ReactNode;normalizeEvents:(event:string)=>VideoEvent|null}
export function normalizeYouTubeMediaId(value:string){const id=/^[\w-]{11}$/.test(value)?value:(()=>{try{const url=new URL(value);if(url.hostname==="youtu.be")return url.pathname.slice(1);if(["youtube.com","www.youtube.com","m.youtube.com"].includes(url.hostname))return url.pathname.startsWith("/shorts/")?url.pathname.split("/")[2]:url.searchParams.get("v")??"";}catch{}return "";})();if(!/^[\w-]{11}$/.test(id))throw new Error("ID o URL de YouTube no válido");return id;}
function ratio(asset:ContentAsset){const r=asset.aspectRatio;return r.type==="custom"?`${r.width} / ${r.height}`:r.type.replace(":"," / ");}
export function YouTubeVideoPlayer({asset,title}:{asset:ContentAsset;title:string}){let id="";try{id=normalizeYouTubeMediaId(asset.providerMediaId??"");}catch{return <UnsupportedVideoPlayer message="Video todavía no disponible"/>}return <iframe loading="lazy" referrerPolicy="strict-origin-when-cross-origin" allow="accelerometer; autoplay; encrypted-media; picture-in-picture; web-share; fullscreen" allowFullScreen title={title} src={`https://www.youtube-nocookie.com/embed/${id}`} />;}
export function BunnyVideoPlayer({asset,title}:{asset:ContentAsset;title:string}){const libraryId=asset.providerMetadata.libraryId;const videoId=asset.providerMediaId;if(typeof libraryId!=="string"||!/^[0-9]+$/.test(libraryId)||!videoId||!/^[a-f0-9-]{20,40}$/i.test(videoId))return <UnsupportedVideoPlayer message="Video Bunny todavía no configurado"/>;return <iframe loading="lazy" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture; fullscreen" allowFullScreen title={title} src={`https://iframe.mediadelivery.net/embed/${libraryId}/${videoId}`} />;}
export function UnsupportedVideoPlayer({message="Proveedor todavía no disponible"}:{message?:string}){return <div className="video-fallback" role="status">{message}</div>}
export function VideoPlayer({asset,title}:{asset:ContentAsset;title:string}){const player=!isPublishedAsset(asset)?<UnsupportedVideoPlayer message="Asset pendiente de publicación"/>:asset.provider==="youtube"?<YouTubeVideoPlayer asset={asset} title={title}/>:asset.provider==="bunny"?<BunnyVideoPlayer asset={asset} title={title}/>:<UnsupportedVideoPlayer/>;return <section className="video-player" style={{aspectRatio:ratio(asset)}}>{player}</section>}
