import {expect,test} from "@playwright/test";

test("dashboard exposes standard and quick Module 0 entries",async({page})=>{await page.goto("/");await expect(page.getByRole("link",{name:/Abrir módulo/})).toHaveAttribute("href","/demo/modulo-0");await expect(page.getByRole("link",{name:/Hacer una pausa ahora/})).toHaveAttribute("href","/demo/sos")});

test("vertical creator video is lazy, ordered and responsive",async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto("/demo/modulo-0");await expect(page.getByRole("heading",{name:"No le escribas todavía."})).toBeVisible();const navigation=page.locator(".experience-navigator button");expect(await navigation.allTextContents()).toEqual(expect.arrayContaining(["Inicio","Orientación","Video","el método P.A.U.S.A.","Audio","Emoción"]));await page.getByRole("button",{name:"Video",exact:true}).click();await expect(page.getByText("UN MENSAJE DE TU CREADORA",{exact:true})).toBeVisible();await expect(page.getByRole("heading",{name:"Antes de escribirle, vuelve a ti"})).toBeVisible();const player=page.locator(".smart-video-player");await expect(player).toHaveCSS("aspect-ratio","9 / 16");expect((await player.boundingBox())!.width).toBeLessThanOrEqual(340);await expect(page.locator(".smart-video-player iframe")).toHaveCount(0);await page.getByRole("button",{name:"Reproducir Antes de escribirle, vuelve a ti"}).click();const iframe=page.locator(".smart-video-player iframe");await expect(iframe).toHaveAttribute("src",/youtube-nocookie\.com\/embed\/KD4sVeHm1gg/);await expect(page.getByRole("button",{name:"Ver en pantalla completa"})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);await expect(page.getByRole("button",{name:"Conocer el método P.A.U.S.A."})).toBeVisible()});

test("quick SOS starts with audio and never exposes the creator video",async({page})=>{await page.goto("/demo/sos");await expect(page.getByText("Audio de emergencia")).toBeVisible();await expect(page.locator(".smart-video-player")).toHaveCount(0);await expect(page.getByText("UN MENSAJE DE TU CREADORA",{exact:true})).toHaveCount(0)});

test("application routes remain protected",async({page})=>{await page.context().clearCookies();await page.goto("/app/modulo-0");await expect(page).toHaveURL(/\/acceso$/);await page.goto("/app/sos");await expect(page).toHaveURL(/\/acceso$/)});
