import { execFileSync } from "node:child_process";
import { and,eq,sql } from "drizzle-orm";
import { afterAll,beforeAll,describe,expect,it } from "vitest";
import { getDb,getPool } from "@/db/client";
import { contentAssets,dayProgress,enrollments,reflectionResponses,sosExecutions,tenantMemberships,user } from "@/db/schema";
import { completeDayOne,ensureBetaEnrollment,getDayOne,saveBlockResponse,saveReflection } from "@/features/progress/service";
import { getTenantAssetMap } from "@/features/content/assets";
import { listSosExecutions,saveSosExecution } from "@/features/sos/service";

const ids=["integration-user-a","integration-user-b"];
describe.sequential("PostgreSQL persistence",()=>{const db=getDb();beforeAll(async()=>{execFileSync(process.execPath,["scripts/migrate.mjs"],{env:process.env,stdio:"ignore"});execFileSync(process.execPath,["scripts/seed.mjs"],{env:process.env,stdio:"ignore"});execFileSync(process.execPath,["scripts/seed.mjs"],{env:process.env,stdio:"ignore"});execFileSync("pnpm",["content:publish"],{env:process.env,stdio:"ignore"});await db.delete(user).where(sql`${user.id} in (${ids[0]},${ids[1]})`);await db.insert(user).values(ids.map((id,index)=>({id,name:"Test",email:`m1-${index}@example.test`,emailVerified:true})));});afterAll(async()=>{await db.delete(user).where(sql`${user.id} in (${ids[0]},${ids[1]})`);await getPool().end();});
  it("seed is idempotent",async()=>{const result=await getPool().query("select count(*)::int as count from tenants where id='mnle'");expect(result.rows[0].count).toBe(1);const days=await getPool().query("select count(*)::int as count from program_days where day_number between 1 and 7");expect(days.rows[0].count).toBe(7);});
  it("auto-enrollment is idempotent",async()=>{await ensureBetaEnrollment(db,"mnle",ids[0]);await ensureBetaEnrollment(db,"mnle",ids[0]);expect((await db.select().from(tenantMemberships).where(and(eq(tenantMemberships.tenantId,"mnle"),eq(tenantMemberships.userId,ids[0])))).length).toBe(1);expect((await db.select().from(enrollments).where(and(eq(enrollments.tenantId,"mnle"),eq(enrollments.userId,ids[0])))).length).toBe(1);});
  it("saves and reloads reflection with tenant and user isolation",async()=>{await ensureBetaEnrollment(db,"mnle",ids[1]);await saveReflection(db,"mnle",ids[0],"Antes del impulso siento mucha ansiedad.");expect((await getDayOne(db,"mnle",ids[0])).response).toContain("ansiedad");expect((await getDayOne(db,"mnle",ids[1])).response).toBe("");});
  it("completes day one idempotently",async()=>{await saveBlockResponse(db,"mnle",ids[0],{blockId:"day-1-scale",value:5});await saveBlockResponse(db,"mnle",ids[0],{blockId:"day-1-checklist",value:["detonante","emocion","necesidad"]});await saveBlockResponse(db,"mnle",ids[0],{blockId:"day-1-action",value:true});await completeDayOne(db,"mnle",ids[0],"Antes del impulso siento mucha ansiedad.");await completeDayOne(db,"mnle",ids[0],"Antes del impulso siento mucha ansiedad.");const enrollment=(await db.select().from(enrollments).where(eq(enrollments.userId,ids[0])))[0];expect((await db.select().from(dayProgress).where(and(eq(dayProgress.enrollmentId,enrollment.id),eq(dayProgress.status,"completed")))).length).toBe(1);expect((await db.select().from(reflectionResponses).where(and(eq(reflectionResponses.userId,ids[0]),eq(reflectionResponses.tenantId,"mnle")))).length).toBe(1);});
  it("resolves only sanitized assets from the current tenant",async()=>{await getPool().query("INSERT INTO tenants(id,slug,product_name,short_name,status,branding) SELECT 'other','other','Other','Other','active',branding FROM tenants WHERE id='mnle' ON CONFLICT DO NOTHING");await db.insert(contentAssets).values([{tenantId:"mnle",key:"local-audio",category:"audio",provider:"file",providerMetadata:{privateToken:"never"},title:"Audio",aspectRatio:{type:"3:4"},sourceUrl:"/media/audio.mp3",mediaType:"audio/mpeg",status:"ready",contentVersion:"1",sourceHash:"a"},{tenantId:"other",key:"other-only",category:"video",provider:"vimeo",providerMetadata:{secret:"never"},title:"Other",aspectRatio:{type:"16:9"},status:"ready",contentVersion:"1",sourceHash:"b"}]).onConflictDoNothing();const assets=await getTenantAssetMap(db,"mnle");expect(assets["local-audio"].sourceUrl).toBe("/media/audio.mp3");expect(assets["other-only"]).toBeUndefined();expect(assets["local-audio"].providerMetadata).toEqual({});});
  it("SOS keeps separate private executions without changing progress",async()=>{const before=(await db.select().from(dayProgress).where(eq(dayProgress.tenantId,"mnle"))).length;const log=console.log;await saveSosExecution(db,"mnle",ids[0],{messageText:"mensaje privado",expectedResponse:"expectativa privada",desiredOutcome:"claridad",emotionBefore:8,completed:false});await saveSosExecution(db,"mnle",ids[0],{messageText:"otro mensaje",expectedResponse:"otra expectativa",desiredOutcome:"alivio",emotionBefore:6,emotionAfter:4,completed:true});expect((await listSosExecutions(db,"mnle",ids[0])).length).toBe(2);expect((await listSosExecutions(db,"mnle",ids[1])).length).toBe(0);expect((await db.select().from(dayProgress).where(eq(dayProgress.tenantId,"mnle"))).length).toBe(before);expect(console.log).toBe(log);await db.delete(sosExecutions).where(eq(sosExecutions.userId,ids[0]));});
});
