import { relations, sql } from "drizzle-orm";
import { bigint, boolean, index, integer, jsonb, pgEnum, pgTable, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core";
import type { ContentBlock } from "@/features/content/schema";

const timestamps = { createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() };

export const user = pgTable("user", { id:text("id").primaryKey(), name:text("name").notNull(), email:text("email").notNull().unique(), emailVerified:boolean("email_verified").default(false).notNull(), image:text("image"), ...timestamps });
export const session = pgTable("session", { id:text("id").primaryKey(), expiresAt:timestamp("expires_at",{withTimezone:true}).notNull(), token:text("token").notNull().unique(), ...timestamps, ipAddress:text("ip_address"), userAgent:text("user_agent"), userId:text("user_id").notNull().references(()=>user.id,{onDelete:"cascade"}) }, (t)=>[index("session_user_id_idx").on(t.userId)]);
export const account = pgTable("account", { id:text("id").primaryKey(), accountId:text("account_id").notNull(), providerId:text("provider_id").notNull(), userId:text("user_id").notNull().references(()=>user.id,{onDelete:"cascade"}), accessToken:text("access_token"), refreshToken:text("refresh_token"), idToken:text("id_token"), accessTokenExpiresAt:timestamp("access_token_expires_at",{withTimezone:true}), refreshTokenExpiresAt:timestamp("refresh_token_expires_at",{withTimezone:true}), scope:text("scope"), password:text("password"), ...timestamps },(t)=>[index("account_user_id_idx").on(t.userId)]);
export const verification = pgTable("verification", { id:text("id").primaryKey(), identifier:text("identifier").notNull(), value:text("value").notNull(), expiresAt:timestamp("expires_at",{withTimezone:true}).notNull(), ...timestamps },(t)=>[index("verification_identifier_idx").on(t.identifier)]);
export const rateLimit = pgTable("rate_limit", { id:text("id").primaryKey(), key:text("key").notNull().unique(), count:integer("count").notNull(), lastRequest:bigint("last_request",{mode:"number"}).notNull() });

export const tenantStatus = pgEnum("tenant_status",["active","inactive"]);
export const programStatus = pgEnum("program_status",["active","inactive"]);
export const dayStatus = pgEnum("day_status",["available","coming_soon"]);
export const enrollmentStatus = pgEnum("enrollment_status",["active","completed","cancelled"]);
export const progressStatus = pgEnum("progress_status",["not_started","in_progress","completed"]);

export const tenants = pgTable("tenants", { id:text("id").primaryKey(), slug:text("slug").notNull().unique(), productName:text("product_name").notNull(), shortName:text("short_name").notNull(), status:tenantStatus("status").default("active").notNull(), branding:jsonb("branding").$type<Record<string,string>>().notNull(), ...timestamps });
export const tenantDomains = pgTable("tenant_domains", { id:uuid("id").defaultRandom().primaryKey(), tenantId:text("tenant_id").notNull().references(()=>tenants.id,{onDelete:"cascade"}), hostname:text("hostname").notNull().unique(), isPrimary:boolean("is_primary").default(false).notNull(), createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull() },(t)=>[index("tenant_domains_tenant_idx").on(t.tenantId)]);
export const tenantMemberships = pgTable("tenant_memberships", { id:uuid("id").defaultRandom().primaryKey(), tenantId:text("tenant_id").notNull().references(()=>tenants.id,{onDelete:"cascade"}), userId:text("user_id").notNull().references(()=>user.id,{onDelete:"cascade"}), role:text("role").default("member").notNull(), createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull() },(t)=>[uniqueIndex("tenant_memberships_tenant_user_uq").on(t.tenantId,t.userId),index("tenant_memberships_user_idx").on(t.userId)]);
export const programs = pgTable("programs", { id:uuid("id").defaultRandom().primaryKey(), tenantId:text("tenant_id").notNull().references(()=>tenants.id,{onDelete:"cascade"}), slug:text("slug").notNull(), title:text("title").notNull(), description:text("description").notNull(), totalDays:integer("total_days").notNull(), status:programStatus("status").default("active").notNull(), ...timestamps },(t)=>[uniqueIndex("programs_tenant_slug_uq").on(t.tenantId,t.slug),index("programs_tenant_idx").on(t.tenantId)]);
export const programDays = pgTable("program_days", { id:uuid("id").defaultRandom().primaryKey(), programId:uuid("program_id").notNull().references(()=>programs.id,{onDelete:"cascade"}), dayNumber:integer("day_number").notNull(), slug:text("slug").notNull(), title:text("title").notNull(), objective:text("objective").notNull(), status:dayStatus("status").notNull(), contentBlocks:jsonb("content_blocks").$type<ContentBlock[]>().default(sql`'[]'::jsonb`).notNull(), ...timestamps },(t)=>[uniqueIndex("program_days_program_day_uq").on(t.programId,t.dayNumber),index("program_days_program_idx").on(t.programId)]);
export const enrollments = pgTable("enrollments", { id:uuid("id").defaultRandom().primaryKey(), tenantId:text("tenant_id").notNull().references(()=>tenants.id,{onDelete:"cascade"}), programId:uuid("program_id").notNull().references(()=>programs.id,{onDelete:"cascade"}), userId:text("user_id").notNull().references(()=>user.id,{onDelete:"cascade"}), status:enrollmentStatus("status").default("active").notNull(), startedAt:timestamp("started_at",{withTimezone:true}).defaultNow().notNull(), completedAt:timestamp("completed_at",{withTimezone:true}), ...timestamps },(t)=>[uniqueIndex("enrollments_program_user_uq").on(t.programId,t.userId),index("enrollments_tenant_user_idx").on(t.tenantId,t.userId)]);
export const dayProgress = pgTable("day_progress", { id:uuid("id").defaultRandom().primaryKey(), tenantId:text("tenant_id").notNull().references(()=>tenants.id,{onDelete:"cascade"}), enrollmentId:uuid("enrollment_id").notNull().references(()=>enrollments.id,{onDelete:"cascade"}), programDayId:uuid("program_day_id").notNull().references(()=>programDays.id,{onDelete:"cascade"}), status:progressStatus("status").default("not_started").notNull(), startedAt:timestamp("started_at",{withTimezone:true}), completedAt:timestamp("completed_at",{withTimezone:true}), ...timestamps },(t)=>[uniqueIndex("day_progress_enrollment_day_uq").on(t.enrollmentId,t.programDayId),index("day_progress_tenant_enrollment_idx").on(t.tenantId,t.enrollmentId),index("day_progress_day_idx").on(t.programDayId)]);
export const reflectionResponses = pgTable("reflection_responses", { id:uuid("id").defaultRandom().primaryKey(), tenantId:text("tenant_id").notNull().references(()=>tenants.id,{onDelete:"cascade"}), userId:text("user_id").notNull().references(()=>user.id,{onDelete:"cascade"}), enrollmentId:uuid("enrollment_id").notNull().references(()=>enrollments.id,{onDelete:"cascade"}), programDayId:uuid("program_day_id").notNull().references(()=>programDays.id,{onDelete:"cascade"}), promptKey:text("prompt_key").notNull(), responseText:text("response_text").notNull(), ...timestamps },(t)=>[uniqueIndex("reflection_enrollment_day_prompt_uq").on(t.enrollmentId,t.programDayId,t.promptKey),index("reflection_tenant_user_idx").on(t.tenantId,t.userId)]);

export const tenantRelations=relations(tenants,({many})=>({domains:many(tenantDomains),programs:many(programs)}));
