"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { authClient } from "@/lib/auth-client";

export function AccessForm(){const router=useRouter();const [step,setStep]=useState<"email"|"otp">("email");const [email,setEmail]=useState("");const [otp,setOtp]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [canResend,setCanResend]=useState(false);
  async function send(){setBusy(true);setError("");const result=await authClient.emailOtp.sendVerificationOtp({email,type:"sign-in"});setBusy(false);if(result.error){setError("No pudimos enviar el código. Espera un momento e inténtalo otra vez.");return;}setCanResend(false);window.setTimeout(()=>setCanResend(true),60_000);setStep("otp");}
  async function verify(){setBusy(true);setError("");const result=await authClient.signIn.emailOtp({email,otp});setBusy(false);if(result.error){setError("El código no es válido o ya expiró. Revisa los seis dígitos.");return;}router.push("/app");router.refresh();}
  if(step==="email")return <form onSubmit={(event)=>{event.preventDefault();void send();}} className="auth-form"><label htmlFor="email">Email</label><input id="email" name="email" type="email" autoComplete="email" inputMode="email" required value={email} onChange={(event)=>setEmail(event.target.value.trim().toLowerCase())} placeholder="tu@email.com"/><button className="button" disabled={busy}>{busy?"Enviando…":"Enviarme el código"}</button>{error&&<p className="form-error" role="alert">{error}</p>}</form>;
  return <form onSubmit={(event)=>{event.preventDefault();void verify();}} className="auth-form"><p className="sent-note">Enviamos un código de seis dígitos a <strong>{email}</strong>.</p><label htmlFor="otp">Código de acceso</label><input id="otp" name="otp" className="otp-input" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} autoFocus required value={otp} onChange={(event)=>setOtp(event.target.value.replace(/\D/g,"").slice(0,6))} placeholder="000000"/><button className="button" disabled={busy||otp.length!==6}>{busy?"Entrando…":"Entrar"}</button>{error&&<p className="form-error" role="alert">{error}</p>}<div className="auth-links"><button type="button" className="link-button" onClick={()=>{setStep("email");setOtp("");setError("");}}>Cambiar email</button><button type="button" className="link-button" disabled={!canResend||busy} onClick={()=>void send()}>Reenviar código</button></div></form>}
