"use client";
import { useEffect,useState } from "react";
import { PlayIcon } from "./icons";
type DemoState={reflection:string;intensity:number;checks:string[];action:boolean;completed:boolean};
const initial:DemoState={reflection:"",intensity:5,checks:[],action:false,completed:false};
export function DemoDayOne(){const [state,setState]=useState(initial),[ready,setReady]=useState(false);useEffect(()=>{try{const saved=localStorage.getItem("mnle-demo-day-one");if(saved)setState({...initial,...JSON.parse(saved)})}finally{setReady(true)}},[]);useEffect(()=>{if(ready)localStorage.setItem("mnle-demo-day-one",JSON.stringify(state))},[state,ready]);const update=(value:Partial<DemoState>)=>setState(old=>({...old,...value}));return <div className="demo-flow">
  <section className="demo-video" aria-label="Video de demostración"><span className="demo-play"><PlayIcon/></span><div><span className="eyebrow">Una pausa para mirar</span><h2>Antes de enviar: mira el ciclo completo</h2><p>Una introducción visual a tu primer ejercicio.</p></div></section>
  <section className="editorial-copy"><p>El impulso no aparece de la nada. Suele comenzar con un momento, un pensamiento o una sensación que pide alivio inmediato.</p><p>Hoy no necesitas resolver toda la historia. Solo observarla con honestidad y sin juzgarte.</p></section>
  <section className="demo-panel"><span className="step-kicker">01 · OBSERVA</span><h2>¿Qué ocurre justo antes del impulso?</h2><label><span>Tu reflexión</span><textarea value={state.reflection} onChange={e=>update({reflection:e.target.value})} placeholder="Escribe para ti…"/></label></section>
  <section className="demo-panel"><span className="step-kicker">02 · NOMBRA</span><label><strong>¿Qué intensidad tiene hoy el impulso?</strong><output>{state.intensity}</output><input aria-label="¿Qué intensidad tiene hoy el impulso?" type="range" min="1" max="10" value={state.intensity} onChange={e=>update({intensity:Number(e.target.value)})}/></label></section>
  <section className="demo-panel"><span className="step-kicker">03 · RECONOCE</span><h2>Mapa del impulso</h2>{["Identifiqué el detonante","Nombré la emoción","Reconocí la necesidad"].map(item=><label className="demo-check" key={item}><input type="checkbox" checked={state.checks.includes(item)} onChange={e=>update({checks:e.target.checked?[...state.checks,item]:state.checks.filter(x=>x!==item)})}/><span>{item}</span></label>)}</section>
  <section className="demo-action"><span className="step-kicker">PRÓXIMAS 24 HORAS</span><h2>Deja diez minutos entre el impulso y la acción.</h2><p>Anota qué pasó, qué sientes y qué necesitas. No tienes que decidir durante esa pausa.</p><label className="demo-check"><input type="checkbox" checked={state.action} onChange={e=>update({action:e.target.checked})}/><span>Elijo hacer esta pausa</span></label></section>
  <button className="button demo-complete" onClick={()=>update({completed:true})}>{state.completed?"Día 1 completado ✓":"Completar el Día 1"}</button><p className="demo-save-note" aria-live="polite">{ready?"Tus cambios se guardan solo en este dispositivo.":""}</p>
  </div>}
