"use client";
import { useRef, useState } from "react";
import { useRouter } from "next/navigation";

export function ReflectionForm({prompt,initialValue,completed}:{prompt:string;initialValue:string;completed:boolean}){const router=useRouter();const [text,setText]=useState(initialValue);const [state,setState]=useState<"idle"|"saving"|"saved"|"error">(completed?"saved":"idle");const [done,setDone]=useState(completed);const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
  async function save(value:string){if(value.trim().length<10)return;setState("saving");try{const response=await fetch("/api/progress/day-one",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({responseText:value})});if(!response.ok)throw new Error();setState("saved");}catch{setState("error");}}
  function update(value:string){setText(value);setState("idle");if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>void save(value),700);}
  async function complete(){setState("saving");try{const response=await fetch("/api/progress/day-one",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({responseText:text})});if(!response.ok)throw new Error();setDone(true);setState("saved");router.refresh();}catch{setState("error");}}
  return <><section className="reflection"><span className="eyebrow">Pausa para ti</span><h2>{prompt}</h2><textarea aria-label="Tu reflexión" placeholder="Escribe lo que notas, sin juzgarte." rows={6} minLength={10} maxLength={2000} value={text} onChange={(event)=>update(event.target.value)}/><div className="save-status" aria-live="polite">{state==="saving"?"Guardando…":state==="saved"?"Guardado":state==="error"?"No se guardó. Tu texto sigue aquí.":`${text.length}/2000`}</div></section><section className="action-card"><span className="eyebrow">Acción del día</span><h2>{done?"Día 1 completado":"Cuando estés lista"}</h2><p>{done?"Hoy elegiste observar antes de actuar. Vuelve a esta reflexión cuando lo necesites.":"Guarda tu reflexión y cierra este primer paso con una decisión consciente."}</p><button className="button light" type="button" disabled={done||state==="saving"||text.trim().length<10} onClick={()=>void complete()}>{done?"Completado":"Completar el Día 1"}</button></section></>}
