"use client";
import { useEffect,useRef,useState } from "react";
import Link from "next/link";
import { ArrowIcon,PauseIcon,PlayIcon } from "./icons";
import { CreatorAvatar,SmartVideoPlayer } from "./media/smart-video-player";
import { createSosState,type SosExperienceState } from "@/features/sos/types";
import type { SosAssetSources } from "@/features/sos/assets";
import { jannyCreator } from "@/features/media/creator";

const emotions=["Ansiedad","Tristeza","Miedo","Rabia","Soledad","Rechazo","Confusión","Nostalgia","Necesidad de cierre","Quiero saber si le importo","Quiero que me elija","Otra"];
const outcomes=["Amor","Calma","Claridad","Atención","Reconciliación","Validación","Alivio","Otra"];
const actions=["Escuchar otra vez el audio","Escribir sin enviar","Tomar agua","Caminar 10 minutos","Hablar con una amiga segura","Alejarme de WhatsApp 30 minutos","Respirar","Repetir una frase ancla"];
const anchors=["No tengo que resolver mi ansiedad mandando un mensaje.","Extrañarlo no significa que deba buscarlo.","Mi paz también merece una oportunidad.","Si él aparece y desaparece, yo no tengo que desaparecer de mí.","Antes de volver a él, vuelvo a mí."];

export function SosProgress({step}:{step:number}){return <div className="sos-progress" role="progressbar" aria-label="Progreso de la pausa" aria-valuemin={0} aria-valuemax={8} aria-valuenow={step}><span style={{"--sos-progress":`${step/8*100}%`} as React.CSSProperties}/></div>}
export function SosTimer({endsAt,onSkip,demo}:{endsAt:string;onSkip:()=>void;demo:boolean}){const [now,setNow]=useState(()=>Date.now());useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id)},[]);const seconds=Math.max(0,Math.ceil((new Date(endsAt).getTime()-now)/1000));return <div className="sos-compact-timer"><span>Tiempo de pausa</span><strong>{Math.floor(seconds/60)}:{String(seconds%60).padStart(2,"0")}</strong>{demo&&seconds>0&&<button onClick={onSkip}>Continuar ahora</button>}</div>}
export function SosChoiceChips({items,selected,multiple=false,onChange,label}:{items:string[];selected:string[];multiple?:boolean;onChange:(value:string[])=>void;label:string}){function choose(item:string){onChange(multiple?(selected.includes(item)?selected.filter(x=>x!==item):[...selected,item]):[item])}return <fieldset className="sos-choice"><legend>{label}</legend><div>{items.map(item=>{const active=selected.includes(item);return <button type="button" key={item} className={active?"selected":""} aria-pressed={active} onClick={()=>choose(item)}>{active&&<span aria-hidden="true">✓</span>}{item}</button>})}</div></fieldset>}
export function SosBreathingGuide(){return <div className="sos-breathing"><span aria-hidden="true"><i/></span><div><strong>Haz tres respiraciones lentas.</strong><small>Inhala suave. Exhala un poco más largo.</small></div></div>}
export function SosRealityExercise({state,update}:{state:SosExperienceState;update:(value:Partial<SosExperienceState>)=>void}){return <div className="sos-fields"><label>Lo que realmente pasó<textarea value={state.realFact} onChange={e=>update({realFact:e.target.value})}/></label><label>Lo que mi ansiedad está imaginando<textarea value={state.anxietyStory} onChange={e=>update({anxietyStory:e.target.value})}/></label><SosChoiceChips label="¿Qué parte está hablando ahora?" items={["Mi calma","Mi miedo","Mi herida","No lo sé todavía"]} selected={state.speakingPart?[state.speakingPart]:[]} onChange={v=>update({speakingPart:v[0]??""})}/></div>}
export function SosSafeAction({value,onChange}:{value:string;onChange:(value:string)=>void}){return <SosChoiceChips label="Elige una salida segura para esta emoción" items={actions} selected={value?[value]:[]} onChange={v=>onChange(v[0]??"")}/>}
export function SosUnsentMessage({state,update}:{state:SosExperienceState;update:(value:Partial<SosExperienceState>)=>void}){return <div className="sos-fields"><label>Lo que yo quería decirle era…<textarea value={state.unsentMessage} onChange={e=>update({unsentMessage:e.target.value})}/></label><label>Lo que realmente quería que me respondiera era… <small>Opcional</small><textarea value={state.expectedResponse} onChange={e=>update({expectedResponse:e.target.value})}/></label>{state.messageSaved&&<p className="sos-confirmation" role="status">Tu emoción salió. El mensaje no fue enviado.</p>}</div>}
export function SosAnchorPhrase({value,onChange}:{value:string;onChange:(value:string)=>void}){return <div className="anchor-list" role="radiogroup" aria-label="Elige una frase ancla">{anchors.map(anchor=><button type="button" role="radio" aria-checked={value===anchor} className={value===anchor?"selected":""} key={anchor} onClick={()=>onChange(anchor)}><span>{anchor}</span><b aria-hidden="true">{value===anchor?"♥":"♡"}</b></button>)}</div>}
export function SosResult({assets,dayHref,onReplay}:{assets:SosAssetSources;dayHref:string;onReplay:()=>void}){return <div className="sos-result"><span className="result-mark" aria-hidden="true">P.A.U.S.A.</span><h1>No actuaste en automático.</h1><p>Tal vez todavía duele. Pero hiciste algo diferente: pausaste, escuchaste tu emoción y volviste a ti.</p><blockquote>Durante los próximos 10 minutos elegiste no enviar el mensaje desde la ansiedad.</blockquote><Link className="button" href={dayHref}>Continuar con el Día 1 <ArrowIcon/></Link><button className="sos-secondary" onClick={onReplay}><PlayIcon/> Volver a escuchar el audio</button><a className="sos-guide-link" href={assets.guide} target="_blank" rel="noreferrer">Descargar la guía completa</a></div>}
export function CreatorAudioPlayer({src,duration,onStarted}:{src:string;duration:number;onStarted?:()=>void}){const audio=useRef<HTMLAudioElement>(null),[playing,setPlaying]=useState(false),[time,setTime]=useState(0),[speed,setSpeed]=useState(1);useEffect(()=>{const pause=()=>{audio.current?.pause();setPlaying(false)};window.addEventListener("smart-video-play",pause);return()=>window.removeEventListener("smart-video-play",pause)},[]);async function toggle(){if(!audio.current)return;if(audio.current.paused){window.dispatchEvent(new CustomEvent("smart-video-play",{detail:"mnle-sos-audio"}));await audio.current.play();setPlaying(true);onStarted?.()}else{audio.current.pause();setPlaying(false)}}function changeSpeed(){const next=speed===1?1.25:1;setSpeed(next);if(audio.current)audio.current.playbackRate=next}return <div className={`sos-audio ${playing?"playing":""}`}><audio ref={audio} src={src} preload="metadata" controls onTimeUpdate={e=>setTime(e.currentTarget.currentTime)} onEnded={()=>setPlaying(false)}/><CreatorAvatar creator={jannyCreator}/><button className="sos-audio-play" onClick={()=>void toggle()} aria-label={playing?"Pausar audio":"Reproducir audio"}>{playing?<PauseIcon/>:<PlayIcon/>}</button><div><strong>Janny</strong><span>Audio de emergencia · 0:{String(duration).padStart(2,"0")}</span><div className="audio-track"><i style={{"--audio-progress":`${Math.min(100,time/duration*100)}%`} as React.CSSProperties}/></div><small>{Math.floor(time/60)}:{String(Math.floor(time%60)).padStart(2,"0")} / 0:{String(duration).padStart(2,"0")}</small></div><button className="audio-speed" onClick={changeSpeed}>{speed===1.25?"1.25×":"1×"}</button></div>}

export function SosStepShell({step,title,intro,children,accent="neutral"}:{step:string;title:string;intro?:string;children:React.ReactNode;accent?:"warm"|"lavender"|"cool"|"primary"|"neutral"}){return <section className={`sos-step step-${accent}`}><span className="sos-letter">{step}</span><h1>{title}</h1>{intro&&<p className="sos-intro">{intro}</p>}{children}</section>}

export function SosExperience({mode,assets,initialState,dayHref}:{mode:"demo"|"authenticated";assets:SosAssetSources;initialState?:SosExperienceState;dayHref:string}){const demo=mode==="demo",[state,setState]=useState<SosExperienceState>(()=>initialState??createSosState()),[hydrated,setHydrated]=useState(!demo),[saving,setSaving]=useState(false),[showVideo,setShowVideo]=useState(false);useEffect(()=>{if(!demo)return;try{const raw=localStorage.getItem("mnle.demo.sos.v1");if(raw)setState({...createSosState(),...JSON.parse(raw)})}finally{setHydrated(true)}},[demo]);useEffect(()=>{if(demo&&hydrated)localStorage.setItem("mnle.demo.sos.v1",JSON.stringify(state))},[demo,hydrated,state]);function update(value:Partial<SosExperienceState>){setState(old=>({...old,...value}))}async function persist(next:SosExperienceState){if(demo){localStorage.setItem("mnle.demo.sos.v1",JSON.stringify(next));return next}setSaving(true);try{const response=await fetch("/api/sos",{method:next.executionId?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(next.executionId?{id:next.executionId,state:next}:next)});if(!response.ok)return next;const body=await response.json() as {id:string};return {...next,executionId:body.id}}finally{setSaving(false)}}async function go(step:number,extra:Partial<SosExperienceState>={}){const next={...state,...extra,step};setState(await persist(next));window.scrollTo({top:0,behavior:"smooth"})}function skip(){update({pauseEndsAt:new Date().toISOString()})}const common={state,update};return <div className="sos-experience"><SosProgress step={state.step}/><header className="sos-experience-top"><Link href={demo?"/":"/app"} aria-label="Cerrar pausa">×</Link><SosTimer endsAt={state.pauseEndsAt} demo={demo} onSkip={skip}/></header><main className="sos-stage">
{state.step===0&&<SosStepShell step="Módulo 0 · Antes de escribirle, vuelve a ti" title="No le escribas todavía." intro="No tienes que decidir nada ahora. Solo quédate contigo durante los próximos 10 minutos." accent="primary"><CreatorAudioPlayer src={assets.audio} duration={assets.duration}/>{showVideo&&<div className="sos-video-reveal"><SmartVideoPlayer asset={assets.video} creator={jannyCreator} context="sos" resumePlayback={demo}/></div>}<p className="sos-notice">Esta experiencia ofrece una pausa guiada y no sustituye atención profesional o de emergencia.</p></SosStepShell>}
{state.step===1&&<SosStepShell step="P" title="Pon el celular boca abajo." accent="warm"><ul className="sos-instructions"><li>Apoya los pies en el piso.</li><li>Suelta los hombros.</li><li>Relaja la mandíbula.</li></ul><SosBreathingGuide/><label className="sos-textarea">En este momento quiero escribirle porque…<textarea value={state.pauseReason} onChange={e=>update({pauseReason:e.target.value})}/></label></SosStepShell>}
{state.step===2&&<SosStepShell step="A" title="Ponle nombre a lo que sientes." accent="lavender"><SosChoiceChips label="Puedes elegir más de una" items={emotions} multiple selected={state.emotions} onChange={v=>update({emotions:v})}/><label className="sos-range">¿Qué tan intenso se siente el impulso?<strong>{state.initialIntensity}</strong><input aria-label="Intensidad inicial" type="range" min="1" max="10" value={state.initialIntensity} onChange={e=>update({initialIntensity:Number(e.target.value)})}/></label><SosChoiceChips label="¿Qué esperas recibir con su respuesta?" items={outcomes} selected={state.expectedOutcome?[state.expectedOutcome]:[]} onChange={v=>update({expectedOutcome:v[0]??""})}/></SosStepShell>}
{state.step===3&&<SosStepShell step="U" title="Separa el hecho de la historia." accent="cool"><SosRealityExercise {...common}/></SosStepShell>}
{state.step===4&&<SosStepShell step="S" title="La emoción necesita salida. No necesariamente hacia él." accent="warm"><SosSafeAction value={state.safeAction} onChange={value=>update({safeAction:value})}/></SosStepShell>}
{state.step===5&&<SosStepShell step="" title="Escríbelo. Pero no lo pongas en sus manos."><SosUnsentMessage {...common}/></SosStepShell>}
{state.step===6&&<SosStepShell step="A" title="Antes de volver a él, vuelve a ti." intro="Si me elijo en este momento, lo que necesito es…" accent="primary"><SosAnchorPhrase value={state.selectedAnchor} onChange={value=>update({selectedAnchor:value})}/></SosStepShell>}
{state.step===7&&<SosStepShell step="" title="¿Cómo estás ahora?"><label className="sos-range">Intensidad ahora<strong>{state.finalIntensity}</strong><input aria-label="Intensidad final" type="range" min="1" max="10" value={state.finalIntensity} onChange={e=>update({finalIntensity:Number(e.target.value)})}/></label><div className="traffic-options">{(["green","yellow","red"] as const).map((value,index)=><button type="button" key={value} className={`${value} ${state.trafficLightResult===value?"selected":""}`} onClick={()=>update({trafficLightResult:value})}><i/><strong>{["Puedo esperar.","Todavía quiero escribirle.","Me siento demasiado removida."][index]}</strong><span>{["No necesito escribir ahora.","Reconozco que estoy activada.","No voy a decidir; buscaré apoyo seguro."][index]}</span></button>)}</div>{state.trafficLightResult==="yellow"&&<p className="traffic-note">Activa tu regla de 24 horas: hoy no envías nada.</p>}{state.trafficLightResult==="red"&&<p className="traffic-note">Repite el audio y busca apoyo inmediato de una persona de confianza, un profesional o los servicios de emergencia de tu país si estás en riesgo.</p>}</SosStepShell>}
{state.step===8&&<SosResult assets={assets} dayHref={dayHref} onReplay={()=>void go(0)}/>}</main>
{state.step<8&&<footer className="sos-sticky-actions">{state.step>0&&<button className="sos-back" onClick={()=>void go(state.step-1)}>Atrás</button>}{state.step===0?<><button className="button" onClick={()=>void go(1)}>Escuchar y comenzar mi P.A.U.S.A.</button><button className="sos-secondary" onClick={()=>setShowVideo(value=>!value)}>{showVideo?"Volver al audio":"Ver el mensaje de Janny"}</button><button className="sos-tertiary" onClick={()=>void go(1)}>Continuar sin audio</button></>:state.step===5&&!state.messageSaved?<button className="button" disabled={!state.unsentMessage.trim()} onClick={()=>{update({messageSaved:true});void persist({...state,messageSaved:true})}}>Guardar sin enviar</button>:<button className="button" disabled={state.step===2&&(!state.emotions.length||!state.expectedOutcome)||state.step===4&&!state.safeAction||state.step===6&&!state.selectedAnchor||state.step===7&&!state.trafficLightResult} onClick={()=>void go(state.step+1,state.step===7?{status:"completed",completedAt:new Date().toISOString()}: {})}>{state.step===1?"Ya hice la pausa":state.step===4?"Elegir esta acción":state.step===5?"Continuar":state.step===7?"Cerrar mi P.A.U.S.A.":"Continuar"}</button>}{saving&&<span className="sos-saving">Guardando…</span>}</footer>}
{demo&&state.step===8&&<button className="clear-demo" onClick={()=>{localStorage.removeItem("mnle.demo.sos.v1");localStorage.removeItem(`experience-player:sos:${assets.video.key}`);setState(createSosState())}}>Borrar mi demostración</button>}</div>}
