import Link from "next/link";
import { ArrowIcon,PauseIcon } from "./icons";

export function TodayHero({eyebrow,title,description}:{eyebrow:string;title:string;description:string}){return <header className="today-hero"><div className="hero-light" aria-hidden="true"><i/><i/><i/></div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></header>}

export function NextStepCard({label,title,description,href,action,completed=0,total=7,percent=0,preparation=false}:{label:string;title:string;description:string;href?:string;action?:string;completed?:number;total?:number;percent?:number;preparation?:boolean}){return <section className="next-step-card"><div className="next-step-texture" aria-hidden="true"/><div className="next-step-content"><div className="editorial-index"><strong>{preparation?"00":"01"}</strong><span>{label}</span></div><h2>{title}</h2><p>{description}</p><div className="integrated-progress"><span>{preparation?"Tu espacio de preparación está listo.":completed===0?"Tu primer paso está listo.":`${completed} de ${total} · ${percent} %`}</span><small>{preparation?"Siempre disponible":completed===0?"Día 1 de 7":"Tu recorrido"}</small>{!preparation&&completed>0&&<i style={{"--progress":`${percent}%`} as React.CSSProperties}/>}</div>{href&&action&&<Link className="next-step-cta" href={href}><span>{action}</span><ArrowIcon/></Link>}</div></section>}

export function CompactProgress({completed,total,percent,message}:{completed:number;total:number;percent:number;message:string}){return <section className="compact-progress" aria-label="Progreso del recorrido"><div className="progress-summary"><strong>{completed} de {total}</strong><span>{percent} %</span></div><div className="progress-track" role="progressbar" aria-valuemin={0} aria-valuemax={100} aria-valuenow={percent} aria-label={`${percent}% completado`}><span style={{"--progress":`${percent}%`} as React.CSSProperties}/></div><p>{message}</p></section>}

export function SosQuickAction({question,subtitle="Toma una pausa guiada.",action,href}:{question:string;subtitle?:string;action:string;href:string}){return <Link href={href} className="sos-quick-action"><span className="sos-icon"><PauseIcon/></span><span><strong>{question}</strong><small>{subtitle}</small><b>{action}</b></span><ArrowIcon className="sos-arrow"/></Link>}
