"use client";
import { useEffect,useRef } from "react";
import type { PlayerController,PlayerEvent,PlayerSnapshot } from "./player-types";

type YTPlayer={playVideo:()=>void;pauseVideo:()=>void;seekTo:(n:number,a:boolean)=>void;mute:()=>void;unMute:()=>void;setVolume:(n:number)=>void;setPlaybackRate:(n:number)=>void;getCurrentTime:()=>number;getDuration:()=>number;getVolume:()=>number;isMuted:()=>boolean;destroy:()=>void};
declare global {interface Window {YT?:{Player:new(element:HTMLElement,options:Record<string,unknown>)=>YTPlayer};onYouTubeIframeAPIReady?:()=>void}}
let apiPromise:Promise<void>|undefined;
function loadApi(){if(window.YT?.Player)return Promise.resolve();if(apiPromise)return apiPromise;apiPromise=new Promise((resolve,reject)=>{const previous=window.onYouTubeIframeAPIReady;window.onYouTubeIframeAPIReady=()=>{previous?.();resolve()};const script=document.createElement("script");script.src="https://www.youtube.com/iframe_api";script.async=true;script.onerror=()=>reject(new Error("YouTube API unavailable"));document.head.appendChild(script)});return apiPromise}
export function YouTubePlayerAdapter({videoId,title,resumeAt,onEvent,onController,onFailure}:{videoId:string;title:string;resumeAt:number;onEvent:(event:PlayerEvent,snapshot?:Partial<PlayerSnapshot>)=>void;onController:(controller:PlayerController)=>void;onFailure:()=>void}){const mount=useRef<HTMLDivElement>(null);useEffect(()=>{let active=true,player:YTPlayer|undefined,timer:ReturnType<typeof setInterval>|undefined;const container=mount.current,target=document.createElement("div");container?.appendChild(target);void loadApi().then(()=>{if(!active||!container||!window.YT)return;player=new window.YT.Player(target,{host:"https://www.youtube-nocookie.com",videoId,playerVars:{autoplay:0,controls:0,enablejsapi:1,playsinline:1,rel:0,origin:window.location.origin},events:{onReady:()=>{if(!player)return;if(resumeAt>0)player.seekTo(resumeAt,true);onController({play:()=>player?.playVideo(),pause:()=>player?.pauseVideo(),seek:n=>player?.seekTo(n,true),setMuted:value=>value?player?.mute():player?.unMute(),setVolume:value=>player?.setVolume(value*100),setRate:value=>player?.setPlaybackRate(value)});onEvent("ready",{ready:true,duration:player.getDuration(),volume:player.getVolume()/100,muted:player.isMuted()});player.playVideo();timer=setInterval(()=>{if(player)onEvent("progress",{currentTime:player.getCurrentTime(),duration:player.getDuration()})},500)},onStateChange:(event:{data:number})=>{if(event.data===1)onEvent("play",{playing:true});if(event.data===2)onEvent("pause",{playing:false});if(event.data===0)onEvent("completed",{playing:false,currentTime:0})},onError:()=>{onEvent("error");onFailure()}}});}).catch(()=>{onEvent("error");onFailure()});return()=>{active=false;if(timer)clearInterval(timer);player?.destroy();container?.replaceChildren()}},[onController,onEvent,onFailure,resumeAt,title,videoId]);return <div ref={mount} className="youtube-player-mount" data-testid="youtube-player-mount"/>}
