import type { TenantConfig } from "@/features/tenants/types";

export type EmailTemplateName = "auth-otp"|"welcome"|"daily-reminder"|"event-invitation"|"creator-response";
export type TemplateVariables = Record<string,string|undefined>;
export interface RenderedEmail { subject:string;previewText:string;html:string;text:string }
const escape=(value:string)=>value.replace(/[&<>"']/g,(char)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[char]!);
const required=(variables:TemplateVariables,key:string)=>{const value=variables[key];if(!value)throw new Error(`Missing email template variable: ${key}`);return value;};

function content(template:EmailTemplateName,tenant:TenantConfig,v:TemplateVariables){
  switch(template){
    case "auth-otp": {const code=required(v,"code");return {subject:`Tu código para entrar a ${tenant.productName}`,previewText:"Tu código seguro expira en cinco minutos.",heading:"Tu espacio está aquí",body:`Hola. Usa este código para entrar: <strong style="font-size:30px;letter-spacing:6px">${escape(code)}</strong><br><br>Expira en cinco minutos. Por seguridad, no lo compartas. Si no lo solicitaste, puedes ignorar este mensaje.`,text:`Hola. Tu código para entrar es ${code}. Expira en cinco minutos. Por seguridad, no lo compartas. Si no lo solicitaste, puedes ignorar este mensaje.`};}
    case "welcome": return {subject:`Bienvenida a ${tenant.productName}`,previewText:"Tu experiencia ya está lista.",heading:`Bienvenida a ${tenant.productName}`,body:`Tu espacio está listo. A continuación podrás avanzar a tu ritmo y retomar donde lo dejaste.<br><br>${cta(required(v,"appUrl"),"Abrir la app",tenant)}`,text:`Bienvenida a ${tenant.productName}. Tu espacio está listo. Abre la app: ${required(v,"appUrl")}`};
    case "daily-reminder": {const greeting=v.name?`Hola, ${escape(v.name)}.`:"Hola.";return {subject:v.subject??`Tu siguiente paso en ${tenant.productName}`,previewText:required(v,"dayTitle"),heading:required(v,"dayTitle"),body:`${greeting} ${escape(required(v,"action"))}<br><br>${cta(required(v,"appUrl"),"Continuar",tenant)}`,text:`${v.name?`Hola, ${v.name}.`:"Hola."} ${required(v,"dayTitle")}. ${required(v,"action")} ${required(v,"appUrl")}`};}
    case "event-invitation": return {subject:v.subject??`Invitación: ${required(v,"eventName")}`,previewText:`${required(v,"date")} · ${required(v,"time")}`,heading:required(v,"eventName"),body:`${escape(required(v,"date"))} · ${escape(required(v,"time"))} (${escape(required(v,"timezone"))})<br><br>${escape(required(v,"description"))}<br><br>${cta(required(v,"eventUrl"),"Reservar o abrir evento",tenant)}`,text:`${required(v,"eventName")}. ${required(v,"date")} a las ${required(v,"time")} (${required(v,"timezone")}). ${required(v,"description")} ${required(v,"eventUrl")}`};
    case "creator-response": return {subject:v.subject??`${required(v,"creatorName")} respondió en ${tenant.productName}`,previewText:"Tienes una nueva respuesta.",heading:`Una respuesta de ${required(v,"creatorName")}`,body:`${escape(required(v,"response"))}<br><br>${cta(required(v,"appUrl"),"Ver dentro de la app",tenant)}`,text:`${required(v,"creatorName")}: ${required(v,"response")} ${required(v,"appUrl")}`};
  }
}
function cta(url:string,label:string,tenant:TenantConfig){return `<a href="${escape(url)}" style="display:inline-block;padding:13px 20px;border-radius:${escape(tenant.branding.radius.button)};background:${tenant.branding.colors.primary};color:${tenant.branding.colors.primaryForeground};text-decoration:none;font-weight:700">${label}</a>`;}
export function renderEmailTemplate(tenant:TenantConfig,template:EmailTemplateName,variables:TemplateVariables):RenderedEmail {const rendered=content(template,tenant,variables);const b=tenant.branding;const logo=b.assets.logo?`<img src="${escape(b.assets.logo)}" alt="${escape(tenant.productName)}" style="max-height:44px;max-width:180px">`:`<strong>${escape(tenant.productName)}</strong>`;return {...rendered,html:`<!doctype html><html><body style="margin:0;background:${b.colors.background};color:${b.colors.text};font-family:${escape(b.typography.bodyFont)}"><span style="display:none">${escape(rendered.previewText)}</span><main style="max-width:600px;margin:auto;padding:32px 20px"><section style="padding:28px;border:1px solid ${b.colors.border};border-radius:${escape(b.radius.card)};background:${b.colors.surface}">${logo}<h1 style="font-family:${escape(b.typography.headingFont)};color:${b.colors.text}">${escape(rendered.heading)}</h1><div style="color:${b.colors.textMuted};line-height:1.6">${rendered.body}</div></section><p style="color:${b.colors.textMuted};font-size:12px">${escape(tenant.productName)} · ${escape(b.supportEmail)}</p></main></body></html>`};}
