"use client";
import Link from "next/link";
import { useMemo,useRef,useState } from "react";
import type { ContentAsset,ContentBlock,CreatorMetadata,ExperienceSection as SectionDefinition,ModuleContentDocument } from "@/features/content/schema";
import { ContentBlockRenderer } from "@/features/content/renderer";
import { CreatorAvatar,SmartVideoPlayer } from "@/components/media/smart-video-player";

type Answers=Record<string,string|string[]|number|boolean>;
type SectionProps={section:SectionDefinition;assets:Record<string,ContentAsset>;answers:Answers;onAnswer:(key:string,value:Answers[string])=>void};

export function ExperienceCover({section}:Pick<SectionProps,"section">){return <header className="experience-cover"><span>{section.eyebrow}</span><h1>{section.title}</h1>{section.description&&<p>{section.description}</p>}</header>}
export function ExperienceNavigator({sections,current,onSelect}:{sections:SectionDefinition[];current:number;onSelect:(index:number)=>void}){return <div className="experience-navigation"><div className="experience-section-progress" role="progressbar" aria-label="Progreso por secciones" aria-valuemin={1} aria-valuemax={sections.length} aria-valuenow={current+1}><span>{current+1} / {sections.length}</span><i style={{"--experience-progress":`${(current+1)/sections.length*100}%`} as React.CSSProperties}/></div><nav className="experience-navigator" aria-label="Contenido de la experiencia">{sections.map((section,index)=><button key={section.id} aria-current={current===index?"step":undefined} onClick={()=>onSelect(index)}>{section.navigationLabel??section.title}</button>)}</nav></div>}

function ResponseBlock({block,value,onChange}:{block:ContentBlock;value:Answers[string]|undefined;onChange:(value:Answers[string])=>void}){switch(block.type){case "textInput":return <label>{block.label}<input required={block.required} value={String(value??"")} onChange={event=>onChange(event.target.value)}/></label>;case "textarea":return <label>{block.label}<textarea required={block.required} value={String(value??"")} onChange={event=>onChange(event.target.value)}/></label>;case "singleChoice":case "multiChoice":{const selected=Array.isArray(value)?value:value?[String(value)]:[];return <fieldset><legend>{block.label}</legend>{block.options.map(option=><label key={option.value}><input type={block.type==="singleChoice"?"radio":"checkbox"} checked={selected.includes(option.value)} onChange={()=>onChange(block.type==="singleChoice"?option.value:selected.includes(option.value)?selected.filter(item=>item!==option.value):[...selected,option.value])}/>{option.label}</label>)}</fieldset>}case "scale":return <label>{block.label}<output>{Number(value??block.min)}</output><input type="range" min={block.min} max={block.max} value={Number(value??block.min)} onChange={event=>onChange(Number(event.target.value))}/></label>;case "checklist":{const selected=Array.isArray(value)?value:[];return <fieldset><legend>{block.title}</legend>{block.items.map(item=><label key={item.id}><input type="checkbox" checked={selected.includes(item.id)} onChange={()=>onChange(selected.includes(item.id)?selected.filter(value=>value!==item.id):[...selected,item.id])}/>{item.label}</label>)}</fieldset>}default:return null}}
function SectionBlocks(props:SectionProps){return <div className="experience-blocks">{props.section.blocks.map(block=>["textInput","textarea","singleChoice","multiChoice","scale","checklist"].includes(block.type)?<ResponseBlock key={block.id} block={block} value={props.answers[block.id]} onChange={value=>props.onAnswer(block.id,value)}/>:block.type==="action"&&block.href?<Link key={block.id} className="button" href={block.href}>{block.title}</Link>:<ContentBlockRenderer key={block.id} block={block} assets={props.assets}/>)}</div>}
function BaseSection(props:SectionProps){return <section className="experience-section"><span>{props.section.eyebrow}</span>{props.section.title&&<h1>{props.section.title}</h1>}{props.section.description&&<p>{props.section.description}</p>}<SectionBlocks {...props}/></section>}
export function ConceptSection(props:SectionProps){return <BaseSection {...props}/>}
export function ExampleSection(props:SectionProps){return <BaseSection {...props}/>}
export function GuidedPracticeSection(props:SectionProps){return <BaseSection {...props}/>}
export function ResourceSection(props:SectionProps){return <BaseSection {...props}/>}
export function NextStepSection(props:SectionProps){return <BaseSection {...props}/>}
export function CreatorAudioPlayer({asset,creator}:{asset:ContentAsset;creator:CreatorMetadata}){const audio=useRef<HTMLAudioElement>(null),[playing,setPlaying]=useState(false);async function toggle(){if(!audio.current)return;if(audio.current.paused){window.dispatchEvent(new CustomEvent("smart-video-play",{detail:asset.key}));await audio.current.play();setPlaying(true)}else{audio.current.pause();setPlaying(false)}}return <div className="creator-audio-player"><audio ref={audio} src={asset.sourceUrl} preload="metadata" onEnded={()=>setPlaying(false)}/><CreatorAvatar creator={creator}/><button type="button" onClick={()=>void toggle()} aria-label={playing?"Pausar audio":"Reproducir audio"}>{playing?"Ⅱ":"▶"}</button><div><strong>{creator.displayName}</strong><span>{creator.role}</span><small>{asset.title}</small></div></div>}
export function CreatorMediaSection(props:SectionProps){const media=props.section.blocks.find(block=>block.type==="video"||block.type==="audio");const asset=media&&"assetRef" in media&&media.assetRef?props.assets[media.assetRef]:undefined;return <section className="experience-section creator-media-section"><span>{props.section.eyebrow}</span>{props.section.title&&<h1>{props.section.title}</h1>}{props.section.description&&<p>{props.section.description}</p>}{asset&&props.section.creator&&media?.type==="video"&&<SmartVideoPlayer asset={asset} creator={props.section.creator} context={props.section.id} resumePlayback/>}{asset?.sourceUrl&&props.section.creator&&media?.type==="audio"&&<CreatorAudioPlayer asset={asset} creator={props.section.creator}/>}<div className="experience-blocks">{props.section.blocks.filter(block=>block!==media).map(block=><ContentBlockRenderer key={block.id} block={block} assets={props.assets}/>)}</div></section>}
export function PersonalResultSection(props:SectionProps){const result=props.section.result;const matches=result?.rules.filter(rule=>(!rule.when||props.answers[rule.when.responseKey]===rule.when.equals)&&(!rule.anchorResponseKey||props.answers[rule.anchorResponseKey]!==undefined))??[];return <section className="experience-section personal-result-section"><span>{props.section.eyebrow}</span><h1>{result?.title??props.section.title}</h1>{result?.summary&&<p>{result.summary}</p>}{matches.map((rule,index)=><article key={index}><h2>{rule.title}</h2>{rule.body&&<p>{rule.body}</p>}{rule.anchorResponseKey&&props.answers[rule.anchorResponseKey]!==undefined&&<blockquote>{Array.isArray(props.answers[rule.anchorResponseKey])?(props.answers[rule.anchorResponseKey] as string[]).join(", "):String(props.answers[rule.anchorResponseKey])}</blockquote>}</article>)}<SectionBlocks {...props}/></section>}
export function ExperienceSectionRenderer(props:SectionProps){switch(props.section.type){case "cover":return <><ExperienceCover section={props.section}/><SectionBlocks {...props}/></>;case "creator_message":case "media":return <CreatorMediaSection {...props}/>;case "concept":return <ConceptSection {...props}/>;case "example":return <ExampleSection {...props}/>;case "practice":return <GuidedPracticeSection {...props}/>;case "result":return <PersonalResultSection {...props}/>;case "resources":return <ResourceSection {...props}/>;case "next_step":return <NextStepSection {...props}/>;default:return <BaseSection {...props}/>}}
export function ExperienceSection(props:SectionProps){return <div className={`experience-tone-${props.section.tone}`}><ExperienceSectionRenderer {...props}/></div>}
export function ExperienceEngine({experience,assets,entryMode="standard",closeHref="/"}:{experience:ModuleContentDocument;assets:Record<string,ContentAsset>;entryMode?:"standard"|"quick";closeHref?:string}){const sections=useMemo(()=>{const published=experience.sections?.filter(section=>section.status==="published")??[],boundary=published.findIndex(section=>section.type==="next_step");if(entryMode==="standard")return boundary>=0?published.slice(0,boundary+1):published;const quick=boundary>=0?published.slice(boundary+1):[];return quick.length?quick:published.slice(Math.max(0,published.findIndex(section=>section.type==="practice")))},[entryMode,experience.sections]);const [current,setCurrent]=useState(0),[answers,setAnswers]=useState<Answers>({});const section=sections[current];if(!section)return null;return <div className={`experience-engine mode-${experience.presentationMode} entry-${entryMode}`}><header className="experience-top"><Link href={closeHref} aria-label="Cerrar">×</Link><ExperienceNavigator sections={sections} current={current} onSelect={setCurrent}/></header><main><ExperienceSection section={section} assets={assets} answers={answers} onAnswer={(key,value)=>setAnswers(old=>({...old,[key]:value}))}/></main><footer className="experience-actions">{current>0&&<button onClick={()=>setCurrent(value=>value-1)}>Atrás</button>}{current<sections.length-1&&<button className="button" onClick={()=>setCurrent(value=>value+1)}>Continuar</button>}</footer></div>}
export function hasQuickEntry(experience:ModuleContentDocument){return experience.entryModes.includes("quick")}
export type { CreatorMetadata };
